= To Deploy Mule Artifacts to a Central Maven Repository (Mule Maven Plugin)

Using a central repository can save users' time when building applications. To deploy to a central repository, you need to deploy the Mule POM files and JAR artifacts to the desired repository.

== To deploy the pom.xml`

In your Mule installation, locate the file <MULE_HOME>/bin/populate_m2_repo.groovy and open it for editing. Locate the following line:

[source, code, linenums]
----
mvn(["install:install-file",
 "-DgroupId=${project.groupId}", "-DartifactId=${project.artifactId}",
"-Dversion=${version}", "-Dpackaging=pom",
"-Dfile=${localPom.canonicalPath}"])
----

Modifiy the line as shown.

[source, code, linenums]
----
mvn(["deploy:deploy-file",
 "-DgroupId=${project.groupId}", "-DartifactId=${project.artifactId}",
"-Dversion=${version}", "-Dpackaging=pom",
"-Dfile=${localPom.canonicalPath}","-Durl=http://<your_repository_ip>/nexus/content/repositories/releases", "-DrepositoryId=releases"])
----

For the -Durl parameter, replace your_repository_ip with the correct IP address.

== To deploy the JARs

In the  <MULE_HOME>/bin/populate_m2_repo.groovy file, locate the second // Install pom via maven comment. Immediately below this line is the argument definition, which reads as shown below.

[source, code, linenums]
----
def args = ["install:install-file", "-DgroupId=${pomProps.groupId}", "-DartifactId=${pomProps.artifactId}", "-Dversion=${pomProps.version}", "-Dpackaging=jar", "-Dfile=${f.canonicalPath}", "-DpomFile=${localPom.canonicalPath}"]
----

Modify this line as shown.

[source, code, linenums]
----
def args = ["deploy:deploy-file",
 "-DgroupId=${pomProps.groupId}", "-DartifactId=${pomProps.artifactId}",
 "-Dversion=${pomProps.version}", "-Dpackaging=jar",
"-Dfile=${f.canonicalPath}", "-DpomFile=${localPom.canonicalPath}",
"-Durl=http://${your_repository_ip}/nexus/content/repositories/releases", "-DrepositoryId=releases"]
----

For the -Durl parameter, replace your_repository_ip with the correct IP address.

If you wish to both install the JARs locally and deploy them remotely, you can keep both locations in the argument definition.
